import Head from 'next/head'
import { useState } from 'react';
import User from '../components/User'
import styles from '../styles/Home.module.css'

export default function Home({ userData }) {
  const [detail, setDetail] = useState("")
  console.log(userData);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          <input name='detail' type="text" value={detail} onChange={e => setDetail(e.target.value.toLowerCase())}/>
        </div>
        <User userData={userData} detail={detail}/>
      </main>

      <footer>
        <h2>Footer</h2>
      </footer>
    </div>
  )
}

export async function  getStaticProps() {
  const response = await fetch("https://jsonplaceholder.typicode.com/users")
  const data = await response.json()

  return{
      props:{
          userData: data
      }
  }
}
