import Head from "next/head";
import { useState } from "react";
import User from "../components/User";
import styles from "../styles/Home.module.css";

export default function Home({ userData }) {
  const [detail, setDetail] = useState("");
  console.log(userData);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className=' w-full bg-teal-500 p-5'>
        <h1 className=' font-bold text-2xl text-white text-center w-full '>
          User Details
        </h1>
      </div>

      <div className='flex justify-center'>
        <div className='p-6 flex justify-center w-2/4'>
          <label></label>
          <input
            type='search'
            className='form-control relative flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-teal-500 focus:outline-none'
            onChange={(e) => setDetail(e.target.value.toLowerCase())}
          ></input>
          <button
            name='button'
            className='btn inline-block px-6 py-2.5 bg-teal-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-teal-500 hover:bg-teal-600 focus:bg-teal-500  focus:shadow-lg focus:outline-none focus:ring-0 active:bg-teal-500 active:shadow-lg transition duration-150 ease-in-out flex items-center'
            type='button'
            id='button-addon2'
          >
            <svg
              xmlns='http://www.w3.org/2000/svg'
              className='h-5 w-5'
              viewBox='0 0 20 20'
              fill='currentColor'
            >
              <path
                fillRule='evenodd'
                d='M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z'
                clipRule='evenodd'
              />
            </svg>
          </button>
        </div>
      </div>

      <div>
        <User userData={userData} detail={detail} />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await response.json();

  return {
    props: {
      userData: data,
    },
  };
}
